language: node_js
dist: jammy
node_js:
  - 18

script:
  - echo "Running dummy tests..."
  - echo "Tests passed!"

deploy:
  provider: lambda
  function_name: "dummy-lambda-function"
  region: "us-east-1"
  role: "arn:aws:iam::123456789012:role/dummy_role"
  runtime: "nodejs18.x"
  handler_name: "index.handler"
  zip: "dummy_function.zip"
  on:
    branch: main
  edge: true  # force dpl v2
